### ISSUE TITLE
How can i build a example project?

### ISSUE THREAD

**Issue by Jzone315** [slaclab/surf#545]
Hi:
   I am trying to rebuild a Caui4Core project using the ruckus.tcl inside the directory, and i am using the Vivado 2019.1.3 on Win10 systems, when the source the tcl file, it shows something error below:
ERROR: [Runs 36-335] 'D:/Ref_design/surf/surf/ethernet/Caui4Core/gtyUltraScale+/ip/Caui4GtyIpCore156MHz.dcp' is not a valid design checkpoint
so, did i do something wrong, how can i build a example project？
Thanks a lot.

**Comment by ruck314** [comment]
I suspect that if you open your existing git clone of `Caui4GtyIpCore156MHz.dcp` that it's not a .dcp binary file but pointer to a github lfs database.  The .dcp files in surf firmware library are stored as "git-lfs".  We recommend to do a "git-lfs install" before cloning the repos:
https://github.com/slaclab/dev-board-examples#before-you-clone-the-git-repository
After doing 'git-lfs install` you will either need to make a fresh new clone or `git lfs pull`
https://github.com/git-lfs/git-lfs/wiki/Tutorial

**Comment by Jzone315** [comment]
The "git-lfs" i think is using on the linux machine, but since i only have a windows machine, so is there any way that i can clone and rebuild the example design.
Thanks.

**Comment by ruck314** [comment]
I have done it on Windows before in the past via two methods:

1) TortoiseGit
After doing all the steps of setting up TortoiseGit, then download and install the git-lfs-windows-1.X.X.exe. After that open Git Bash and execute this command:

```
$ git lfs install
> Git LFS initialized.
```

2) Window Subsystem Linux (WSL):

https://docs.google.com/presentation/d/1efwETvXg1q2obzvHkyyXXqjxfSSPNaZSmsE21-1yelk

I wrote this while WSL was still beta, which is not the case anymore. And in the future WSL2 will be the successor to WSL:
https://www.google.com/amp/s/scotch.io/bar-talk/trying-the-new-wsl-2-its-fast-windows-subsystem-for-linux/amp

**Comment by Jzone315** [comment]
I had fixed the issue now, thanks a lot.
